version: '1.0.{build}'
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: buB5GYn0hg4DBCzR3pCyLIbc8Jgg4R3oqLmy9+TXMnrfXBgRye9a+KmOOgh/Few2
before_build:
  - nuget restore ".\ReCaptcha.sln"
build:
  project: .\ReCaptcha.sln
  verbosity: minimal
  publish_nuget: true
test:
  assemblies:
    - ReCaptcha.UnitTests
after_test:
  - ps: .\coveralls.ps1
notifications:
  - provider: Email
    to:
      - devadmin@certegy.com.au
      - ryan.bartsch@certegy.com.au
  - provider: Slack
    auth_token:
      secure: QWE2vFI2LUFAu+jx4lXHihtpPFoVi+ru0mHSC/BvsyXYcRvgh7Tc8zEEaKkj1n5V09+Ti39CvVooS3Y8VTn7PYC6lef2OrQQ+ivqkJL+lZI=
    channel: '#alerts'